---
engines:
  eslint:
    enabled: true,
    channel: "eslint-2"
  ratings:
    paths:
      - "**.js"
  duplication:
    enabled: true
    exclude_paths:
      - node_modules/
    config:
      languages:
        javascript:
          mass_threshold: 20
ratings:
  paths: []
exclude_paths: []
