engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc
      extensions:
        - .es6
        - .js
        - .jsx
  duplication:
    enabled: true
    exclude_paths:
      - node_modules/
    config:
      languages:
        javascript:
          mass_threshold: 20
  ratings:
    paths:
      - "**.es6"
      - "**.js"
      - "**.jsx"
exclude_paths: []
